name: Keep Alive
on:
  schedule:
    - cron: '0 * * * *' # هر یک ساعت اجرا شود
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping repository
        run: echo "Repository is active"
