name: Update

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - run: pip install requests
      
      - name: Run script
        env:
          BALE_TOKEN: ${{ secrets.BALE_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        # مسیر را به درستی تنظیم کنید (اگر اسکریپت در پوشه config است)
        run: python .config/scraper.py

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # اضافه کردن تمام فایل‌های تولید شده (sub1, sub2, sub3 و all_configs)
          git add sub*.txt all_configs.txt
          
          # بررسی تغییرات
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes detected."
          else
            git commit -m "Update sub files - $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          fi
