name: Update
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4  # اضافه کردن این خط
        with:
          node-version: '24'          # اجبار به استفاده از نسخه جدید
      - uses: actions/setup-python@v5
        with: {python-version: '3.9'}
      - run: pip install requests
      - run: python scraper.py
      - run: |
          git config --global user.name 'bot'
          git config --global user.email 'bot@bot.com'
          git add subscription.txt
          git commit -m "update" || exit 0
          git push
